AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  testing-rest-api
  Sample SAM Template for testing-rest-api

Globals:
  Function:
    Timeout: 3
    Tracing: Active

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: preprod
      EndpointConfiguration:
        Type: REGIONAL
              
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetEmployees:
          Type: Api
          Properties:
            Path: /employee
            Method: get
            RestApiId:
              Ref: RestApi
        CreateEmployee:
          Type: Api
          Properties:
            Path: /employee
            Method: post
            RestApiId:
              Ref: RestApi
